# Generated by Django 5.2.12 on 2026-03-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_img',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
