# Generated by Django 5.2.13 on 2026-04-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_claim_sale_detail_alter_sale_sale_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
