# Generated by Django 5.2.13 on 2026-06-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_claim_claim_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='delivered_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='exported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
