# Generated by Django 5.2.12 on 2026-07-22 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_promotion_remove_unit_unit_id_remove_unit_unit_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(max_length=30)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Completed', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sale', models.ForeignKey(db_column='sale_id', on_delete=django.db.models.deletion.CASCADE, to='store.sale')),
            ],
            options={
                'db_table': 'tb_payments',
            },
        ),
    ]
