# Generated by Django 5.2.16 on 2026-07-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
