# Generated by Django 5.2.12 on 2026-07-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_payment_bank_name_payment_reference_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Quotation', 'ໃບສະເໜີລາຄາ'), ('Paid', 'ຊຳລະແລ້ວ'), ('Partial', 'ຊຳລະບາງສ່ວນ'), ('Unpaid', 'ຄ້າງຊຳລະ')], default='Paid', max_length=20),
        ),
    ]
