from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('products/', views.product_list, name='product_list'),
    path('add_to_cart/<str:pro_id>/', views.add_to_cart, name='add_to_cart'),
    path('clear_cart/', views.clear_cart, name='clear_cart'),
    path('pos/', views.pos, name='pos'),
    path('checkout/', views.checkout, name='checkout'),
    path('receipt/<str:sale_id>/', views.receipt, name='receipt'),
    # path('sales/', views.sale_list, name='sale_list'),
    path('all-reports/', views.all_reports, name='all_reports'),
    path('claims/', views.claim_list, name='claim_list'),
    path('claims/add/', views.add_claim, name='add_claim'),
    path('remove-from-cart/<str:pro_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('shop-settings/', views.shop_settings, name='shop_settings'),
    path('import-stock/', views.import_stock, name='import_stock'),
    path('products/add/', views.add_product, name='add_product'),
    path('products/edit/<str:pro_id>/', views.edit_product, name='edit_product'),
    path('products/delete/<str:pro_id>/', views.delete_product, name='delete_product'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('claims/edit/<str:claim_id>/', views.edit_claim, name='edit_claim'),
    path('employees/', views.employee_list, name='employee_list'),
    path('employees/add/', views.add_employee, name='add_employee'),
    path('employees/delete/<str:emp_id>/', views.delete_employee, name='delete_employee'),
    path('categories/', views.category_list, name='category_list'),
    path('brands/', views.brand_list, name='brand_list'),
    path('units/', views.unit_list, name='unit_list'),
    path('categories/delete/<str:cat_id>/', views.delete_category, name='delete_category'),
    path('brands/delete/<str:brand_id>/', views.delete_brand, name='delete_brand'),
    path('units/delete/<str:unit_id>/', views.delete_unit, name='delete_unit'),
    path('suppliers/', views.supplier_list, name='supplier_list'),
    path('suppliers/delete/<str:pk>/', views.delete_supplier, name='delete_supplier'),
    path('supplier/edit/<str:pk>/', views.edit_supplier, name='edit_supplier'),
    path('category/edit/<str:pk>/', views.edit_category, name='edit_category'),
    path('brand/edit/<str:pk>/', views.edit_brand, name='edit_brand'),
    path('unit/edit/<str:pk>/', views.edit_unit, name='edit_unit'),
    path('employee/edit/<str:pk>/', views.employee_edit, name='employee_edit'),
    path('customers/', views.customer_list, name='customer_list'),
    path('customers/edit/<str:cus_id>/', views.edit_customer, name='edit_customer'),
    path('customers/delete/<str:cus_id>/', views.delete_customer, name='delete_customer'),
    path('sale/<str:pk>/', views.sale_detail, name='sale_detail'),
    path('sale/update-status/<str:sale_id>/<str:new_status>/', views.update_sale_status, name='update_sale_status'),
    path('sale/add-shipping/<str:sale_id>/', views.add_shipping, name='add_shipping'),
    path('sale/add-shipping/<str:sale_id>/', views.add_shipping, name='add_shipping'),
]
