# Generated by Django 5.2.12 on 2026-03-04 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cus_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cus_name', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'tb_customers',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_employees',
            },
        ),
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('shop_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop_logo/')),
            ],
            options={
                'db_table': 'tb_shop_info',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('sup_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'tb_suppliers',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_units',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pro_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=100)),
                ('price_buy', models.FloatField()),
                ('price_sale', models.FloatField()),
                ('qty', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.CASCADE, to='store.brand')),
                ('cat', models.ForeignKey(db_column='cat_id', on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('unit', models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.CASCADE, to='store.unit')),
            ],
            options={
                'db_table': 'tb_products',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.FloatField()),
                ('status', models.CharField(default='Paid', max_length=20)),
                ('cus', models.ForeignKey(db_column='cus_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('emp', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, to='store.employee')),
            ],
            options={
                'db_table': 'tb_sales',
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('pro', models.ForeignKey(db_column='pro_id', on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('sale', models.ForeignKey(db_column='sale_id', on_delete=django.db.models.deletion.CASCADE, to='store.sale')),
            ],
            options={
                'db_table': 'tb_sale_details',
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('claim_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('claim_date', models.DateTimeField(auto_now_add=True)),
                ('symptom', models.TextField()),
                ('status', models.CharField(default='Processing', max_length=30)),
                ('emp', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, to='store.employee')),
                ('sale_detail', models.ForeignKey(db_column='sale_detail_id', on_delete=django.db.models.deletion.CASCADE, to='store.saledetail')),
            ],
            options={
                'db_table': 'tb_claims',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('ship_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ship_date', models.DateTimeField(auto_now_add=True)),
                ('tracking_no', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('sale', models.OneToOneField(db_column='sale_id', on_delete=django.db.models.deletion.CASCADE, to='store.sale')),
            ],
            options={
                'db_table': 'tb_shippings',
            },
        ),
        migrations.CreateModel(
            name='StockImport',
            fields=[
                ('imp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('imp_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.FloatField()),
                ('emp', models.ForeignKey(db_column='emp_id', on_delete=django.db.models.deletion.CASCADE, to='store.employee')),
                ('sup', models.ForeignKey(db_column='sup_id', on_delete=django.db.models.deletion.CASCADE, to='store.supplier')),
            ],
            options={
                'db_table': 'tb_stock_imports',
            },
        ),
        migrations.CreateModel(
            name='ImportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('pro', models.ForeignKey(db_column='pro_id', on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('imp', models.ForeignKey(db_column='imp_id', on_delete=django.db.models.deletion.CASCADE, to='store.stockimport')),
            ],
            options={
                'db_table': 'tb_import_details',
            },
        ),
    ]
