# Generated by Django 5.2.12 on 2026-03-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_pro_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=7.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Quotation', 'ໃບສະເໜີລາຄາ'), ('Paid', 'ຊຳລະແລ້ວ'), ('Unpaid', 'ຄ້າງຊຳລະ')], default='Paid', max_length=20),
        ),
    ]
