# Generated by Django 5.2.13 on 2026-04-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_sale_discount_sale_vat_rate_alter_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
